import CustomMongoose from "./custom-mongoose";
import FormatTemplateString from "./format-template-string";
import Global from "./global";
import Logger from "./logger";
import Rest from "./rest";
import Api from "./api";
import Notifier from './notifier';
import { AppSetting } from "../app/config";
const CONFIG = AppSetting.getConfig();
const SchemaDefiner = require(`./schemaDefiners/${CONFIG.DB.DB_TYPE}`).default;
export { Notifier, CustomMongoose, FormatTemplateString, Global, Logger, Rest, Api, SchemaDefiner };
